name: Inject Cache
description: "Injects the cached data into the docker build(x|kit) process"
inputs:
  cache-source:
    default: cache
    description: "Where the cache is stored in the calling workspace. Default: `cache`"
  scratch-dir:
    default: scratch
    description: "Where the action is stores some temporary files for its processing. Default: `scratch`"
runs:
  using: composite
  steps:
    - name: Clean Directories
      shell: bash
      run: |
        rm -Rf ${{ inputs.scratch-dir }} && mkdir -p ${{ inputs.scratch-dir }} ${{ inputs.cache-source }}
    - name: Prepare Timestamp for Layer Cache Busting
      shell: bash
      run: |
        date --iso=ns | tee ${{ inputs.cache-source }}/buildstamp
    - name: Prepare Dancefile to Access Caches
      shell: bash
      run: |
        cat > ${{ inputs.scratch-dir }}/Dancefile.inject <<EOF
        FROM busybox:1
        COPY buildstamp buildstamp
        RUN --mount=type=cache,target=/usr/local/cargo/registry/index \
            --mount=type=cache,target=/usr/local/cargo/registry/cache \
            --mount=type=cache,target=/usr/local/cargo/git/db \
            --mount=type=cache,target=/platform/target \
            --mount=type=bind,source=.,target=/var/dance-cache \
            mkdir -p /usr/local/cargo/git/db && \
            ls -lha /var/dance-cache && \
            ls -lha /usr/local/cargo/registry/index && \
            ls -lha /usr/local/cargo/registry/cache && \
            ls -lha /usr/local/cargo/git/db && \
            ls -lha /platform/target && \
            cp -R /var/dance-cache/registry/index/* /usr/local/cargo/registry/index || true && \
            cp -R /var/dance-cache/registry/cache/* /usr/local/cargo/registry/cache || true && \
            cp -R /var/dance-cache/git/db/* /usr/local/cargo/git/db || true && \
            cp -R /var/dance-cache/target/* /platform/target || true && \
            ls -lha /usr/local/cargo/registry/index && \
            ls -lha /usr/local/cargo/registry/cache && \
            ls -lha /usr/local/cargo/git/db && \
            ls -lha /platform/target
        EOF
        cat ${{ inputs.scratch-dir }}/Dancefile.inject
    - name: Inject Data into buildx context
      shell: bash
      run: |
        docker buildx build -f ${{ inputs.scratch-dir }}/Dancefile.inject --tag dance:inject ${{ inputs.cache-source }}
    - name: Clean Directories
      shell: bash
      run: |
        sudo rm -rf ${{ inputs.cache-source }}
