name: Inject Cache
description: "Injects the cached data into the docker build(x|kit) process"
inputs:
  cache-source:
    default: cache
    description: "Where the cache is stored in the calling workspace. Default: `cache`"
  scratch-dir:
    default: scratch
    description: "Where the action is stores some temporary files for its processing. Default: `scratch`"
runs:
  using: composite
  steps:
    - name: Clean Directories
      shell: bash
      run: |
        rm -Rf ${{ inputs.scratch-dir }} && mkdir -p ${{ inputs.scratch-dir }} ${{ inputs.cache-source }}
    - name: Prepare Timestamp for Layer Cache Busting
      shell: bash
      run: |
        date --iso=ns | tee ${{ inputs.cache-source }}/buildstamp
    - name: Prepare Dancefile to Access Caches
      shell: bash
      run: |
        cat > ${{ inputs.scratch-dir }}/Dancefile.inject <<EOF
        FROM peakcom/s5cmd:v2.0.0
        RUN apk add tree
        COPY buildstamp buildstamp
        RUN --mount=type=cache,sharing=shared,id=cargo_registry,target=/usr/local/cargo/registry \
            --mount=type=cache,sharing=shared,id=cargo_git,target=/usr/local/cargo/git \
            --mount=type=cache,sharing=shared,id=deps_target,target=/platform/target/deps \
            --mount=type=cache,sharing=shared,id=drive_target,target=/platform/target/drive \
            /s5cmd sync 's3://platform-runner-cache/cache-mounts/registry/*' '/usr/local/cargo/registry' && \
            /s5cmd sync 's3://platform-runner-cache/cache-mounts/git/*' '/usr/local/cargo/git' && \
            /s5cmd sync 's3://platform-runner-cache/cache-mounts/target/*' '/platform/target' && \
            wait && \
            tree -L 3 /usr/local/cargo && \
            tree -L 3 /platform/target && \
            chmod 777 -R /usr/local/cargo/registry || true && \
            chmod 777 -R /usr/local/cargo/git || true && \
            chmod 777 -R /platform/target || true
        EOF
        cat ${{ inputs.scratch-dir }}/Dancefile.inject
    - name: Inject Data into buildx context
      shell: bash
      run: |
        docker buildx build -f ${{ inputs.scratch-dir }}/Dancefile.inject ${{ inputs.cache-source }}
    - name: Clean Directories
      shell: bash
      run: |
        sudo rm -rf ${{ inputs.cache-source }}
