name: Extract Cache
description: "Extracts the cached data from the docker build(x|kit) process"
inputs:
  cache-source:
    default: cache
    description: "Where the cache is stored in the calling workspace. Default: `cache`"
  scratch-dir:
    default: scratch
    description: "Where the action is stores some temporary files for its processing. Default: `scratch`"
  mounts:
    description: Docker build cache mounts list
    required: true
  bucket:
    description: Bucket name
    required: true

runs:
  using: composite
  steps:
    - name: Prepare Timestamp for Layer Cache Busting
      shell: bash
      run: |
        date --iso=ns | tee ${{ inputs.scratch-dir }}/buildstamp

    - name: Prepare list of cache mounts for Dancefile
      uses: actions/github-script@v6
      id: mounts
      with:
        result-encoding: string
        script: |
          return `${{ inputs.mounts }}`
            .split(/[\r\n,]+/)
            .map((mount) => mount.trim())
            .filter((mount) => mount.length > 0)
            .map((mount) => (
              `--mount=type=cache,sharing=shared,id=${mount},target=/cache-mounts/${mount}`
            ))
            .join(' ');

    - name: Extract cache data from buildx context
      shell: bash
      run: |
        docker build ${{ inputs.scratch-dir }} --file - <<EOF
        FROM amazon/aws-cli:2.13.17
        COPY buildstamp buildstamp
        RUN ${{ steps.mounts.outputs.result }} \
            aws s3 sync --no-follow-symlinks --quiet /cache-mounts s3://${{inputs.bucket}}/cache-mounts
        EOF
