name: Extract Cache
description: "Extracts the cached data from the docker build(x|kit) process"
inputs:
  cache-source:
    default: cache
    description: "Where the cache is stored in the calling workspace. Default: `cache`"
  scratch-dir:
    default: scratch
    description: "Where the action is stores some temporary files for its processing. Default: `scratch`"
runs:
  using: composite
  steps:
    - name: Prepare Timestamp for Layer Cache Busting
      shell: bash
      run: |
        date --iso=ns | tee ${{ inputs.scratch-dir }}/buildstamp
    - name: Prepare Dancefile to Access Caches
      shell: bash
      run: |
        cat > ${{ inputs.scratch-dir }}/Dancefile.extract <<EOF
        FROM peakcom/s5cmd:v2.0.0
        COPY buildstamp buildstamp
        RUN --mount=type=cache,sharing=shared,id=cargo_registry,target=/usr/local/cargo/registry \
            --mount=type=cache,sharing=shared,id=cargo_git,target=/usr/local/cargo/git \
            --mount=type=cache,sharing=shared,id=deps_target,target=/platform/target/deps \
            --mount=type=cache,sharing=shared,id=drive_target,target=/platform/target/drive \
            /s5cmd sync /usr/local/cargo/registry s3://platform-runner-cache/cache-mounts/registry/* && \
            /s5cmd sync /usr/local/cargo/git s3://platform-runner-cache/cache-mounts/git/* && \
            /s5cmd sync /platform/target s3://platform-runner-cache/cache-mounts/target/*
        EOF
        cat ${{ inputs.scratch-dir }}/Dancefile.extract
    - name: Extract Data into buildx context
      shell: bash
      run: |
        docker buildx build -f ${{ inputs.scratch-dir }}/Dancefile.extract ${{ inputs.scratch-dir }}
    # - name: Create Extraction Image
    #   shell: bash
    #   run: |
    #     docker rm -f cache-container && docker create -ti --name cache-container dance:extract
    # - name: Unpack Docker Image into Scratch
    #   shell: bash
    #   run: |
    #     docker cp -L cache-container:/var/dance-cache - | tar -x -C ${{ inputs.scratch-dir }}
    # - name: Move Cache into Its Place
    #   shell: bash
    #   run: |
    #     sudo rm -rf ${{ inputs.cache-source }}
    #     mv ${{ inputs.scratch-dir }}/dance-cache ${{ inputs.cache-source }}
    #     pwd
    #     ls
