name: Extract Cache
description: "Extracts the cached data from the docker build(x|kit) process"
inputs:
  cache-source:
    default: cache
    description: "Where the cache is stored in the calling workspace. Default: `cache`"
  scratch-dir:
    default: scratch
    description: "Where the action is stores some temporary files for its processing. Default: `scratch`"
runs:
  using: composite
  steps:
    - name: Prepare Timestamp for Layer Cache Busting
      shell: bash
      run: |
        date --iso=ns | tee ${{ inputs.scratch-dir }}/buildstamp
    - name: Prepare Dancefile to Access Caches
      shell: bash
      run: |
        cat > ${{ inputs.scratch-dir }}/Dancefile.extract <<EOF
        FROM busybox:1
        COPY buildstamp buildstamp
        RUN --mount=type=cache,sharing=shared,id=deps_cargo_index,target=/deps/usr/local/cargo/registry/index \
            --mount=type=cache,sharing=shared,id=deps_cargo_cache,target=/deps/usr/local/cargo/registry/cache \
            --mount=type=cache,sharing=shared,id=deps_cargo_git,target=/deps/usr/local/cargo/git/db \
            --mount=type=cache,sharing=shared,id=deps_target,target=/deps/platform/target \
            --mount=type=cache,sharing=shared,id=drive_cargo_index,target=/drive/usr/local/cargo/registry/index \
            --mount=type=cache,sharing=shared,id=drive_cargo_cache,target=/drive/usr/local/cargo/registry/cache \
            --mount=type=cache,sharing=shared,id=drive_cargo_git,target=/drive/usr/local/cargo/git/db \
            --mount=type=cache,sharing=shared,id=drive_target,target=/drive/platform/target \
            mkdir -p /var/dance-cache/deps/registry/index && \
            mkdir -p /var/dance-cache/deps/registry/cache && \
            mkdir -p /var/dance-cache/deps/git/db && \
            mkdir -p /var/dance-cache/deps/target && \
            mkdir -p /var/dance-cache/drive/registry/index && \
            mkdir -p /var/dance-cache/drive/registry/cache && \
            mkdir -p /var/dance-cache/drive/git/db && \
            mkdir -p /var/dance-cache/drive/target && \
            ls -lha /deps/usr/local/cargo/registry/index && \
            ls -lha /deps/usr/local/cargo/registry/cache && \
            ls -lha /deps/usr/local/cargo/git/db && \
            ls -lha /deps/platform/target && \
            ls -lha /drive/usr/local/cargo/registry/index && \
            ls -lha /drive/usr/local/cargo/registry/cache && \
            ls -lha /drive/usr/local/cargo/git/db && \
            ls -lha /drive/platform/target && \
            echo "deps timestamps after build, before copy from cachedir" && \
            find /deps/usr/local/cargo/registry/cache/github.com-1ecc6299db9ec823/ -exec stat -c '%n %Y' {} + && \
            echo "drive timestamps after build, before copy from cachedir" && \
            find /drive/usr/local/cargo/registry/cache/github.com-1ecc6299db9ec823/ -exec stat -c '%n %Y' {} + && \
            cp -a /deps/usr/local/cargo/registry/index/. /var/dance-cache/deps/registry/index || true && \
            cp -a /deps/usr/local/cargo/registry/cache/. /var/dance-cache/deps/registry/cache || true && \
            cp -a /deps/usr/local/cargo/git/db/. /var/dance-cache/deps/git/db || true && \
            cp -a /deps/platform/target/. /var/dance-cache/deps/target || true && \
            cp -a /drive/usr/local/cargo/registry/index/. /var/dance-cache/drive/registry/index || true && \
            cp -a /drive/usr/local/cargo/registry/cache/. /var/dance-cache/drive/registry/cache || true && \
            cp -a /drive/usr/local/cargo/git/db/. /var/dance-cache/drive/git/db || true && \
            cp -a /drive/platform/target/. /var/dance-cache/drive/target || true && \
            echo "deps timestamps after build, after copy from cachedir" && \
            find /var/dance-cache/deps/registry/cache/github.com-1ecc6299db9ec823/ -exec stat -c '%n %Y' {} + && \
            echo "drive timestamps after build, after copy from cachedir" && \
            find /var/dance-cache/drive/registry/cache/github.com-1ecc6299db9ec823/ -exec stat -c '%n %Y' {} +
        EOF
        cat ${{ inputs.scratch-dir }}/Dancefile.extract
    - name: Extract Data into buildx context
      shell: bash
      run: |
        docker buildx build -f ${{ inputs.scratch-dir }}/Dancefile.extract --tag dance:extract --load ${{ inputs.scratch-dir }}
    - name: Create Extraction Image
      shell: bash
      run: |
        docker rm -f cache-container && docker create -ti --name cache-container dance:extract
    - name: Unpack Docker Image into Scratch
      shell: bash
      run: |
        docker cp -L cache-container:/var/dance-cache - | tar -x -C ${{ inputs.scratch-dir }}
    - name: Move Cache into Its Place
      shell: bash
      run: |
        sudo rm -rf ${{ inputs.cache-source }}
        mv ${{ inputs.scratch-dir }}/dance-cache ${{ inputs.cache-source }}
        pwd
        ls
